authorized-websites:
  - bbc.com
  - cnbc.com
  - thetimes.com
  - theguardian.com
  - telegraph.co.uk
  - independent.co.uk
  - savills.com
  - struttandparker.com
  - goldcrestlfg.com
  - tilhill.com
  - greshamhouse.com
